### ISSUE TITLE
`javax.annotation.Generated` rather than `javax.annotation.processing.Generated` in Java 11

### ISSUE THREAD

**Issue by UkonnRa** [vert-x3/vertx-grpc-java-compiler#17]
I am using Java 11, but the gengrated file `xxxGrpc` is using Java 8's `@javax.annotation.Generated` rather than new `@javax.annotation.processing.Generated`, any solution to customize the generated code based on the Java version?
```
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.9.0)",
    comments = "Source: user_service.proto")
```

**Comment by sofrec** [comment]
> I am using Java 11, but the gengrated file `xxxGrpc` is using Java 8's `@javax.annotation.Generated` rather than new `@javax.annotation.processing.Generated`, any solution to customize the generated code based on the Java version?
> 
> ```
> @javax.annotation.Generated(
>     value = "by gRPC proto compiler (version 1.9.0)",
>     comments = "Source: user_service.proto")
> ```

Hello , did you find a solution for this issue ?

**Comment by pmlopes** [comment]
Have you seen the new compiler in the `vertx-grpc ` module?

**Comment by vietj** [comment]
as @pmlopes we are not providing a customization of this compiler in 4.0, any generator concern should be addressed to the official generator repo
