### ISSUE TITLE
Update generator to emit Promise interface

### ISSUE THREAD

**Issue by andrm** [vert-x3/vertx-grpc-java-compiler#20]
With 3.8.0 out I want to update to the Promise interface. The grpc code gen should generate Promise based interfaces / stubs also.

**Comment by vietj** [comment]
wdyt @pmlopes ?

**Comment by lispczz** [comment]
@andrm You may have a try at 'io.grpc:protoc-gen-grpc-java' rather than this 'io.vertx:protoc-gen-grpc-java'.   
[This repo](https://github.com/lispczz/vertx-grpc-kotlin-example) is a minimal working example.

**Comment by andrm** [comment]
@lispczz that's the normal generator from grpc, emitting the callback-like stuff (onNext, onCompletet). I liked the Future/AsyncHandler style better.

**Comment by andrm** [comment]
1.25.0 seems to address this.
