### ISSUE TITLE
Return a promise for client stub methods in addition of void

### ISSUE THREAD

**Issue by doctorpangloss** [vert-x3/vertx-grpc-java-compiler#23]
#### Describe the feature

For our convenience, generate client stub methods with the signature

```
Future<Reply> rpcName(Request request);
```

in addition to

```
void rpcName(Request request, Promise<Reply> handler);
```

#### Use cases

Makes using the client far less clunky.

#### Contribution

I can implement this feature if there's a chance my PR actually gets merged. I've tried PRing various vertx projects and I don't think I've ever gotten a merge once.

https://github.com/vert-x3/vertx-grpc-java-compiler/blob/35cc5a787257b08c57d23fdf8309f1a6b70d891f/src/main/cpp/java_generator.cpp#L918

Reopens #20, this is probably what the issue author wanted.

**Comment by pmlopes** [comment]
@doctorpangloss for 4.0.0 this module is deprecated and the new compiler lives in https://github.com/vert-x3/vertx-grpc/blob/master/vertx-grpc-protoc-plugin/src/main/resources/VertxStub.mustache with a easier to maintain and add functionality.

Can you check if the new template already suits your needs?
