### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by ruslansennov** [vert-x3/vertx-grpc-java-compiler#4]
In order to use next version of GRPC in `vertx-grpc` (see vert-x3/vertx-grpc#6) we should release corresponding version of `vertx-grpc-java-compiler`

**Comment by pmlopes** [comment]
@ruslansennov I've 2 PR pending review are any of those the version you need?

**Comment by ruslansennov** [comment]
Yes, 1.3.0 is preferable

**Comment by ruslansennov** [comment]
fixed in a5a93b8672c83771e90c0d63ef1771b018979402
